export enum EVENTS {
  GAME_START = 'GAME_START',
  NEW_ROUND = 'NEW_ROUND',
  MOVE_SEND = 'MOVE_SEND',
  FINISH_GAME = 'FINISH_GAME',
  GAME_INTERRUPT = 'GAME_INTERRUPT',
  MOVE_RECEIVE = 'MOVE_RECEIVE',
  GAME_STARTED = 'GAME_STARTED',
  NEW_ROUND_STARTED = 'NEW_ROUND_STARTED',
  GAME_FINISHED = 'GAME_FINISHED',
  GAME_INTERRUPTED = 'GAME_INTERRUPTED',
  JOIN = 'JOIN',
}
